# Generated by Django 5.1.1 on 2024-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
